books/urls.py
from django.urls import path
from demo import settings
from . import views
app_name='books'

urlpatterns = [
    path('',views.homepage,name="homepage"),
    path('books-details/<int:slug>/',views.bookdetails,name="bookdetails"),
    path('add-items/',views.additem,name="add_item"),
    path('delete-items/<int:slug>/',views.deleteitem,name="delete_item"),
    path('update-items/<int:item_id>/',views.updateitem,name="update_item"),
]

from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

demo/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('books.urls'))
]

books/models.py
from django.db import models

# Create your models here.
class Books(models.Model):
    name=models.CharField(max_length=50)
    des=models.TextField()
    image=models.ImageField(upload_to="bk_pics",max_length=500)
    price=models.IntegerField(default=0)
    
    def __str__(self):
        return self.name
    

books/forms.py
from django import forms
from .models import Books

class BooksForm(forms.ModelForm):
    class Meta:
        model = Books
        fields = ['name', 'des','image', 'price']
        

books/views.py
from django.shortcuts import render
from .models import Books
from django.shortcuts import redirect
from .forms import BooksForm

# Create your views here.
def homepage(request):
    books=Books.objects.all()
    books_with_index = [(index + 1, book) for index, book in enumerate(books)]
    return render(request,"index.html",{'books_with_index':books_with_index})
    

def bookdetails(request,slug):
    book=Books.objects.filter(id=slug).first()
    return render(request,"books.html",{'book':book})

def additem(request):
    if request.method=="POST":
        name=request.POST.get("book_name",None)
        desc=request.POST.get("desc",None)
        image=request.FILES['img']
        price=request.POST.get("price",None)
        book=Books(name=name,des=desc,image=image,price=price)
        book.save()
    return render(request,"add_item.html",{})

def deleteitem(request,slug):
    Books.objects.filter(id=slug).delete()
    return redirect("/")

def updateitem(request, item_id):
    item = Books.objects.filter(id=item_id).first()

    if request.method == 'POST':
        form = BooksForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect("/")
    else:
        form = BooksForm(instance=item)

    return render(request, 'edit_item.html', {'form': form})

templates/add_item.html
{% extends 'base.html' %}
{% block body %}
<h1 class="add-h1">ADD NEW ITEMS</h1>
<div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          <label for="book_name">Book Name</label>
          <input type="text" class="form-control my-input" name="book_name" placeholder="Enter Bok Name">
        </div>
        <div class="form-group">
          <label for="desc">Description</label>
          <input type="text" class="form-control my-input" name="desc" placeholder="Enter Description">
        </div>
        <div class="form-group">
          <label for="img">Image</label>
          <input type="file" class="form-control my-input" name="img">
        </div>
        <div class="form-group">
          <label for="price">Price</label>
          <input type="number" class="form-control my-input" name="price">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
</div>
{% endblock  %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Demo</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">BOOK SHOP</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/">Home</a></li>
      <li><a href="#">About</a></li>
      <li><a href="#">Contact</a></li>
      <li><a href="#">Support</a></li>
      <li><a href="{% url 'books:add_item' %}">Add Item</a></li>
    </ul>
  </div>
</nav>
{% block body %}

{% endblock  %}

</body>
</html>

templates/books.html
{% extends 'base.html' %}
{% block body %}
<div class="container" >
    <img src="{{book.image.url}}" width="300" height="400">
    <div class="card-body">
      <h1 class="card-title">{{book.name}}</h1>
      <p class="card-text">{{book.des}}</p>
      <h4 class="card-title">Price: Rs {{book.price}}</h4>
      <a href="/" class="btn btn-primary">Back</a>
    </div>
  </div>
{% endblock  %}

templates/edit_item.html
{% extends 'base.html' %}
{% block body %}
{% load crispy_forms_tags %}
<h1 class="add-h1">UPDATE ITEMS</h1>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% comment %} {{ form.as_p }} {% endcomment %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">Save changes</button>
            </form>
        </div>
    </div>
</div>
    
{% endblock  %}

templates/index.html
{% extends 'base.html' %}

{% block body %}
{% for index, book in books_with_index %}
    <div class="book-item">
        <div class="book-id{{ index }}">
            <h4>{{ index }}</h4>
        </div>
        <img src="{{ book.image.url }}" width="100" height="100">
        <div class="book-details">
            <a href="{% url 'books:bookdetails' book.id %}">{{ book.name }}</a>
        </div>
        <div class="delete-link">
            <a href="{% url 'books:update_item' book.id %}">Update</a> | 
            <a href="{% url 'books:delete_item' book.id %}">Delete</a>
        </div>
    </div>
    <hr>
{% endfor %}
{% endblock %}